version: "3"

tasks:
  default:
    desc: "* Default if no task is specified; lists available tasks"
    silent: true
    cmds:
      - task --list-all

  doc:
    desc: "Generate go-api documentation"
    generates:
      - doc/api-exported.txt
    sources:
      - ./*.go
    cmds:
      - go doc -all > doc/api-exported.txt

  test:
    desc: "Run all go tests"
    sources:
      - ./*.go
    cmds:
      - go test ./*.go
