version: "3"

tasks:
  default:
    desc: "* Default if no task is specified; lists available tasks"
    silent: true
    cmds:
      - task --list-all

  test:
    desc: "Run all go tests"
    sources:
      - ./*.go
    cmds:
      - go test ./*.go
